version: '3.8'

services:
  web:
    build: .
    container_name: api_realtime_php
    # Docker Compose mapping — lokal 5000 → konteyner 5000
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: "1"
      PORT: "5000"
      DB_HOST: "167.235.222.200"
      DB_PORT: "3306"
      DB_USER: "ulogist1_user_uz"
      DB_PASS: "parol3797A@"
      DB_NAME: "ulogist1_db_uz"
      GOOGLE_MAPS_API_KEY: "AIzaSyAd4rEAQqf58fCJGABqW99teDP9BcuyN08"
    volumes:
      - .:/app
    # JSON‑aray emas, shell‑form — $PORT kengayadi
    command: >
      gunicorn app:app
      --bind 0.0.0.0:$PORT
      --timeout 120
    restart: unless-stopped
